### ISSUE TITLE
json不可用

### ISSUE THREAD

**Issue by liust15** [zxlie/FeHelper#219]
突然不可用了
evalCore.min.js:1 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Vue')
    at evalCore.min.js:1:121612
    at evalCore.min.js:1:113993
<img width="706" alt="image" src="https://user-images.githubusercontent.com/29653431/211552995-fd1932ed-bae4-4a34-9adf-9702f6c095e2.png">

**Comment by wen2go** [comment]
我也是json美化问题，配置无法保存

**Comment by liust15** [comment]
> 我也是json美化问题，配置无法保存，下了老版本的可以了：https://github.com/zxlie/FeHelper/tree/master/apps/static/screenshot/crx

应该是缓存的问题，我后面刷新了几次就好了

**Comment by kaqijiang** [comment]
你是不是使用AlfredWorkflow打开的？

路径发生了变化，更新后即可

https://github.com/kaqijiang/FeHelper-AlfredWorkflow

**Comment by zxlie** [comment]
感谢反馈与建议。维护者已审阅本 issue；为便于列表聚焦未决问题，现先行关闭归档。若在新版本中问题仍存在，或需要继续讨论，请点击 Reopen 或新开 issue，并附上复现步骤、浏览器版本与截图。谢谢支持 FeHelper！
