### ISSUE TITLE
FeHelper会影响京东登陆的滑动验证码

### ISSUE THREAD

**Issue by ajianhouyuan** [zxlie/FeHelper#59]
使用账户登录的方式登陆，然后输入用户名和密码，然后出现滑动验证，此时滑块无法滑动。
非必现，但是概率很高，大概有80%几率

Console日志

Error handling response: TypeError: Cannot read property 'id' of null
    at PageModify (chrome-extension://pkgccpejnmalmdinmhkkfafefagiiiad/page-modifier/content-script.js:1:7994)
    at chrome-extension://pkgccpejnmalmdinmhkkfafefagiiiad/page-modifier/content-script.js:1:8483

**Comment by zxlie** [comment]
感谢反馈与建议。维护者已审阅本 issue；为便于列表聚焦未决问题，现先行关闭归档。若在新版本中问题仍存在，或需要继续讨论，请点击 Reopen 或新开 issue，并附上复现步骤、浏览器版本与截图。谢谢支持 FeHelper！
